### PR TITLE
Add RdataString() to all types already implementing RR interface

### PR DESCRIPTION
**Pull request by UmanShahzad**
Needed a way to gather the rdata as a string minus the header string for a RR, and the only way to really do it for most RRs would be to chop off the header string after calling RR.String(). This PR adds RR.RdataString() so we get it directly, and RR.String() behaves the same in all cases.

### CODE REVIEW

**Comment by miekg** [comment]
This might be what your looking for https://godoc.org/github.com/miekg/dns#Field (not super ideal api, but will get the job done)

**Comment by UmanShahzad** [comment]
@miekg That's not a solution. Just see https://github.com/miekg/dns/pull/1035/files#diff-e871404fd69cab40521d6b2178847cf7R913-R955 or many other types in there with complex RdataString implementations.

**Comment by UmanShahzad** [comment]
@miekg Can you check this out again?

**Comment by tmthrgd** [comment]
@UmanShahzad "Needed a way to gather the rdata as a string minus the header string for a RR," Can you explain why you need this?

**Comment by UmanShahzad** [comment]
@tmthrgd We were loading rdata strings from CZDS/Verisign zonefiles into a db and doing some analysis.

**Comment by tmthrgd** [comment]
@UmanShahzad Not all the records actually have well formed ‘rdata strings’ and some are simply for presentation and subject to change. Without knowing more it sounds like something like JSON encoding the record structs would be more appropriate and stable.

**Pull request closed without merging**
