### PR TITLE
Support TsigProvider for zone transfers

### LINKED ISSUE #1300: XFR is not using the TsigProvider
Even if the `TsigProvider` is set on the connection/transfer struct the read/write functions do not use the provider.

https://github.com/miekg/dns/blob/master/xfr.go#L215-L254

### PR DESCRIPTION
**Pull request by tmthrgd**
This adds `TsigProvider` support to `Transfer`.

I've not added any tests as the existing XFR TSIG code doesn't have any tests and I can't say I understand this code well enough to write any tests myself.

Fixes #1300

/cc @dmavrommatis

### CODE REVIEW

**Comment by tmthrgd** [comment]
@dmavrommatis can you check if this fixes your problem?

**Comment by dmavrommatis** [comment]
I remember when I was looking at this that there were some issues with this approach. 
Without the provider when you create a secret you also pass the `t.Hdr.Name` field to get the algorithm while with the tsigProvider you don't. I can't recall exactly what was the issue though.

**Comment by tmthrgd** [comment]
It's slightly cumbersome, but you can get access to `t.Hdr.Name` from within `TsigProvider`. The first argument `msg` is the exact byte-slice we parsed initially. You could safely do something like this:

```go
m := new(dns.Msg)
m.Unpack(msg)
name := m.IsTsig().Hdr.Name
```

Considering the only way you can get there is to have `Unpack` succeed and `IsTsig()` return non-nil, you don't even need to check the error or return values.

**Comment by dmavrommatis** [comment]
Should be good then. Are you going to do the same for the DNS server to support the TsigProvider? https://github.com/miekg/dns/blob/master/server.go#L715

**Comment by tmthrgd** [comment]
@dmavrommatis That would make sense. I'll do that in another PR.

**Comment by Fattouche** [comment]
What is the status of this being merged? I didn't realize that it already existed and I ended up making my own PR to solve this problem. https://github.com/miekg/dns/pull/1323.

**Comment by tmthrgd** [comment]
I'm withdrawing this in favour of a much nicer implementation.

**Pull request closed without merging**
