### PR TITLE
Refactor server shutdown to call Close() on conn and sync on srv.started

### PR DESCRIPTION
**Pull request by FiloSottile**

### CODE REVIEW

**Comment by FiloSottile** [comment]
By the way this fixes https://travis-ci.org/miekg/dns/jobs/82966726 in #267

**Comment by FiloSottile** [comment]
Or apparently the test actually deadlocks.

**Comment by miekg** [comment]
deadlocks... nice...

**Comment by asergeyev** [comment]
Maybe instead Server should assume some default timeout if it's 0?

**Comment by FiloSottile** [comment]
Mh. Can't reproduce on any platform or figure it out by eye. I blame Travis.

Good to merge, @miekg?

**Comment by FiloSottile** [comment]
Here's testing under stress:

```
$ go test -race
PASS
ok  	github.com/miekg/dns	17.026s
$ go test -race
PASS
ok  	github.com/miekg/dns	19.045s
$ go test -race
PASS
ok  	github.com/miekg/dns	31.320s
```

**Comment by FiloSottile** [comment]
Hah, caught it.

```
SIGQUIT: quit
PC=0x5c2bc2 m=0

goroutine 10 [syscall]:
syscall.Syscall(0x2f, 0x3, 0xc820037998, 0x0, 0xc, 0x0, 0x460894)
	/build/go/tmp/dest/usr/local/go/src/syscall/asm_linux_amd64.s:18 +0x5 fp=0xc820037870 sp=0xc820037868
syscall.recvmsg(0x3, 0xc820037998, 0x0, 0x0, 0x0, 0x0)
	/build/go/tmp/dest/usr/local/go/src/syscall/zsyscall_linux_amd64.go:1739 +0x5e fp=0xc8200378b0 sp=0xc820037870
syscall.Recvmsg(0x3, 0xc82011e600, 0x200, 0x200, 0xc820116210, 0x28, 0x28, 0x0, 0xc8201161e0, 0x0, ...)
	/build/go/tmp/dest/usr/local/go/src/syscall/syscall_linux.go:551 +0x233 fp=0xc8200379d8 sp=0xc8200378b0
net.(*netFD).readMsg(0xc8200d40e0, 0xc82011e600, 0x200, 0x200, 0xc820116210, 0x28, 0x28, 0x0, 0x0, 0x0, ...)
	/build/go/tmp/dest/usr/local/go/src/net/fd_unix.go:282 +0x297 fp=0xc820037af0 sp=0xc8200379d8
net.(*UDPConn).ReadMsgUDP(0xc820026030, 0xc82011e600, 0x200, 0x200, 0xc820116210, 0x28, 0x28, 0x200, 0x7db3c0, 0x1, ...)
	/build/go/tmp/dest/usr/local/go/src/net/udpsock_posix.go:96 +0x1dc fp=0xc820037bf8 sp=0xc820037af0
github.com/miekg/dns.ReadFromSessionUDP(0xc820026030, 0xc82011e600, 0x200, 0x200, 0x200, 0x200, 0x0, 0x0)
	/vagrant/go/src/github.com/miekg/dns/udp.go:47 +0xd2 fp=0xc820037cc0 sp=0xc820037bf8
github.com/miekg/dns.(*Server).readUDP(0xc82010e0e0, 0xc820026030, 0x34630b8a000, 0x0, 0x0, 0x0, 0x4d9e65, 0x0, 0x0)
	/vagrant/go/src/github.com/miekg/dns/server.go:632 +0x1d5 fp=0xc820037d60 sp=0xc820037cc0
github.com/miekg/dns.(*defaultReader).ReadUDP(0xc820026048, 0xc820026030, 0x34630b8a000, 0x0, 0x0, 0x0, 0xc82006eb90, 0x0, 0x0)
	/vagrant/go/src/github.com/miekg/dns/server.go:230 +0x8a fp=0xc820037dd8 sp=0xc820037d60
github.com/miekg/dns.(*Server).serveUDP(0xc82010e0e0, 0xc820026030, 0x0, 0x0)
	/vagrant/go/src/github.com/miekg/dns/server.go:502 +0x2f5 fp=0xc820037ed0 sp=0xc820037dd8
github.com/miekg/dns.(*Server).ActivateAndServe(0xc82010e0e0, 0x0, 0x0)
	/vagrant/go/src/github.com/miekg/dns/server.go:369 +0x443 fp=0xc820037f78 sp=0xc820037ed0
github.com/miekg/dns.RunLocalUDPServer.func1(0xc82010e0e0, 0x7f7cbe5e26f0, 0xc820026030)
	/vagrant/go/src/github.com/miekg/dns/server_test.go:52 +0x2f fp=0xc820037f98 sp=0xc820037f78
runtime.goexit()
	/build/go/tmp/dest/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc820037fa0 sp=0xc820037f98
created by github.com/miekg/dns.RunLocalUDPServer
	/vagrant/go/src/github.com/miekg/dns/server_test.go:54 +0x2e4

goroutine 1 [chan receive]:
testing.RunTests(0x951e38, 0xac4420, 0x7b, 0x7b, 0x1)
	/build/go/tmp/dest/usr/local/go/src/testing/testing.go:562 +0xafa
testing.(*M).Run(0xc820047f00, 0x11)
	/build/go/tmp/dest/usr/local/go/src/testing/testing.go:494 +0xe5
main.main()
	github.com/miekg/dns/_test/_testmain.go:340 +0x210

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/build/go/tmp/dest/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 9 [select]:
github.com/miekg/dns.(*Server).Shutdown(0xc82010e0e0, 0x0, 0x0)
	/vagrant/go/src/github.com/miekg/dns/server.go:425 +0x6e5
github.com/miekg/dns.TestClientEDNS0(0xc82010c090)
	/vagrant/go/src/github.com/miekg/dns/client_test.go:87 +0x7aa
testing.tRunner(0xc82010c090, 0xac4450)
	/build/go/tmp/dest/usr/local/go/src/testing/testing.go:456 +0xdd
created by testing.RunTests
	/build/go/tmp/dest/usr/local/go/src/testing/testing.go:561 +0xaa4

goroutine 25 [chan send]:
github.com/miekg/dns.(*Server).Shutdown.func2(0xc82010e0e0, 0xc82006c660)
	/vagrant/go/src/github.com/miekg/dns/server.go:416 +0x6b
created by github.com/miekg/dns.(*Server).Shutdown
	/vagrant/go/src/github.com/miekg/dns/server.go:419 +0x77b

rax    0x2f
rbx    0xc820001800
rcx    0xffffffffffffffff
rdx    0x0
rdi    0x3
rsi    0xc820037998
rbp    0x0
rsp    0xc820037868
r8     0x0
r9     0x0
r10    0x0
r11    0x246
r12    0xc820037860
r13    0xac6680
r14    0xc820001800
r15    0x0
rip    0x5c2bc2
rflags 0x246
cs     0x33
fs     0x0
gs     0x0
*** Test killed with quit: ran too long (10m0s).
FAIL	github.com/miekg/dns	600.023s
```

**Comment by FiloSottile** [comment]
Ah, I see. Shutdown never happens if the server is listening for a packet.

```go
	for {
		m, s, e := reader.ReadUDP(l, rtimeout)
		select {
		case <-srv.stopUDP:
			return nil
		default:
		}
```

Shutdown should be allowed to close the socket.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [dns] Set high timeouts in serv..." ]
>Hah, caught it.

`github.com/miekg/dns.(*Server).ActivateAndServe(0xc82010e0e0, 0x0, 0x0)`

It's with socket activation?

>
>```
>SIGQUIT: quit
>PC=0x5c2bc2 m=0
>
>goroutine 10 [syscall]:
>syscall.Syscall(0x2f, 0x3, 0xc820037998, 0x0, 0xc, 0x0, 0x460894)
>	/build/go/tmp/dest/usr/local/go/src/syscall/asm_linux_amd64.s:18 +0x5 fp=0xc820037870 sp=0xc820037868
>syscall.recvmsg(0x3, 0xc820037998, 0x0, 0x0, 0x0, 0x0)
>	/build/go/tmp/dest/usr/local/go/src/syscall/zsyscall_linux_amd64.go:1739 +0x5e fp=0xc8200378b0 sp=0xc820037870
>syscall.Recvmsg(0x3, 0xc82011e600, 0x200, 0x200, 0xc820116210, 0x28, 0x28, 0x0, 0xc8201161e0, 0x0, ...)
>	/build/go/tmp/dest/usr/local/go/src/syscall/syscall_linux.go:551 +0x233 fp=0xc8200379d8 sp=0xc8200378b0
>net.(*netFD).readMsg(0xc8200d40e0, 0xc82011e600, 0x200, 0x200, 0xc820116210, 0x28, 0x28, 0x0, 0x0, 0x0, ...)
>	/build/go/tmp/dest/usr/local/go/src/net/fd_unix.go:282 +0x297 fp=0xc820037af0 sp=0xc8200379d8
>net.(*UDPConn).ReadMsgUDP(0xc820026030, 0xc82011e600, 0x200, 0x200, 0xc820116210, 0x28, 0x28, 0x200, 0x7db3c0, 0x1, ...)
>	/build/go/tmp/dest/usr/local/go/src/net/udpsock_posix.go:96 +0x1dc fp=0xc820037bf8 sp=0xc820037af0
>github.com/miekg/dns.ReadFromSessionUDP(0xc820026030, 0xc82011e600, 0x200, 0x200, 0x200, 0x200, 0x0, 0x0)
>	/vagrant/go/src/github.com/miekg/dns/udp.go:47 +0xd2 fp=0xc820037cc0 sp=0xc820037bf8
>github.com/miekg/dns.(*Server).readUDP(0xc82010e0e0, 0xc820026030, 0x34630b8a000, 0x0, 0x0, 0x0, 0x4d9e65, 0x0, 0x0)
>	/vagrant/go/src/github.com/miekg/dns/server.go:632 +0x1d5 fp=0xc820037d60 sp=0xc820037cc0
>github.com/miekg/dns.(*defaultReader).ReadUDP(0xc820026048, 0xc820026030, 0x34630b8a000, 0x0, 0x0, 0x0, 0xc82006eb90, 0x0, 0x0)
>	/vagrant/go/src/github.com/miekg/dns/server.go:230 +0x8a fp=0xc820037dd8 sp=0xc820037d60
>github.com/miekg/dns.(*Server).serveUDP(0xc82010e0e0, 0xc820026030, 0x0, 0x0)
>	/vagrant/go/src/github.com/miekg/dns/server.go:502 +0x2f5 fp=0xc820037ed0 sp=0xc820037dd8
>github.com/miekg/dns.(*Server).ActivateAndServe(0xc82010e0e0, 0x0, 0x0)
>	/vagrant/go/src/github.com/miekg/dns/server.go:369 +0x443 fp=0xc820037f78 sp=0xc820037ed0
>github.com/miekg/dns.RunLocalUDPServer.func1(0xc82010e0e0, 0x7f7cbe5e26f0, 0xc820026030)
>	/vagrant/go/src/github.com/miekg/dns/server_test.go:52 +0x2f fp=0xc820037f98 sp=0xc820037f78
>runtime.goexit()
>	/build/go/tmp/dest/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc820037fa0 sp=0xc820037f98
>created by github.com/miekg/dns.RunLocalUDPServer
>	/vagrant/go/src/github.com/miekg/dns/server_test.go:54 +0x2e4
>
>goroutine 1 [chan receive]:
>testing.RunTests(0x951e38, 0xac4420, 0x7b, 0x7b, 0x1)
>	/build/go/tmp/dest/usr/local/go/src/testing/testing.go:562 +0xafa
>testing.(*M).Run(0xc820047f00, 0x11)
>	/build/go/tmp/dest/usr/local/go/src/testing/testing.go:494 +0xe5
>main.main()
>	github.com/miekg/dns/_test/_testmain.go:340 +0x210
>
>goroutine 17 [syscall, locked to thread]:
>runtime.goexit()
>	/build/go/tmp/dest/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1
>
>goroutine 9 [select]:
>github.com/miekg/dns.(*Server).Shutdown(0xc82010e0e0, 0x0, 0x0)
>	/vagrant/go/src/github.com/miekg/dns/server.go:425 +0x6e5
>github.com/miekg/dns.TestClientEDNS0(0xc82010c090)
>	/vagrant/go/src/github.com/miekg/dns/client_test.go:87 +0x7aa
>testing.tRunner(0xc82010c090, 0xac4450)
>	/build/go/tmp/dest/usr/local/go/src/testing/testing.go:456 +0xdd
>created by testing.RunTests
>	/build/go/tmp/dest/usr/local/go/src/testing/testing.go:561 +0xaa4
>
>goroutine 25 [chan send]:
>github.com/miekg/dns.(*Server).Shutdown.func2(0xc82010e0e0, 0xc82006c660)
>	/vagrant/go/src/github.com/miekg/dns/server.go:416 +0x6b
>created by github.com/miekg/dns.(*Server).Shutdown
>	/vagrant/go/src/github.com/miekg/dns/server.go:419 +0x77b
>
>rax    0x2f
>rbx    0xc820001800
>rcx    0xffffffffffffffff
>rdx    0x0
>rdi    0x3
>rsi    0xc820037998
>rbp    0x0
>rsp    0xc820037868
>r8     0x0
>r9     0x0
>r10    0x0
>r11    0x246
>r12    0xc820037860
>r13    0xac6680
>r14    0xc820001800
>r15    0x0
>rip    0x5c2bc2
>rflags 0x246
>cs     0x33
>fs     0x0
>gs     0x0
>*** Test killed with quit: ran too long (10m0s).
>FAIL	github.com/miekg/dns	600.023s
>```
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/miekg/dns/pull/271#issuecomment-146007169
/Miek

--
Miek Gieben

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [dns] Set high timeouts in serv..." ]
>Ah, I see. Shutdown never happens if the server is listening for a packet.
>
>```go
>	for {
>		m, s, e := reader.ReadUDP(l, rtimeout)
>		select {
>		case <-srv.stopUDP:
>			return nil
>		default:
>		}
>```
>
>Shutdown should be allowed to close the socket.

ok, but why doesn't the timeout kick in here?

/Miek

--
Miek Gieben

**Comment by FiloSottile** [comment]
I set the timeout to an Hour because A) it should not rely on the timeout if it's not testing the timeout and B) the timeout causes a error.

I see now that unblocking that loop is what these lines are meant to do:

```go
	c := &Client{Net: net}
	go c.Exchange(new(Msg), addr) // extra query to help ReadXXX loop to pass
```

I'll try to make the construction a bit cleaner.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [dns] Set high timeouts in serv..." ]
>I see now that unblocking that loop is what these lines are meant to do:

yep. Let's call it a hack :)

>```go
>	c := &Client{Net: net}
>	go c.Exchange(new(Msg), addr) // extra query to help ReadXXX loop to pass
>```
>
>I'll try to make the construction a bit cleaner.

Thanks!

/Miek

--
Miek Gieben

**Comment by FiloSottile** [comment]
There, this should do it.

**Pull request merged**
