### PR TITLE
Add LimitReader to drop excess packets

### PR DESCRIPTION
**Pull request by miekg**
This includes code from #1052 and add a tests

See for further discussion: #997

### CODE REVIEW

**Comment by miekg** [comment]
there 1 problem though, the LimitReader can't be both used in the udp and tcp path without locking (or maybe different counters. That should be OK?)

**Comment by miekg** [comment]
We could also simplify the algo: `goroutines > max => refuse` instead of trying to be smart (I think this has my preference)

**Comment by miekg** [comment]
failing with
~~~
o: downloading golang.org/x/tools v0.0.0-20191216052735-49a3e744a425

go: extracting golang.org/x/tools v0.0.0-20191216052735-49a3e744a425

panic: runtime error: index out of range

goroutine 1 [running]:

go/types.(*Struct).Field(...)

	/home/travis/.gimme/versions/go1.12.14.linux.amd64/src/go/types/type.go:148

main.getTypeStruct(0x704b20, 0xc00080b7a0, 0xc000af13b0, 0xf, 0xc00096a368)

	/home/travis/gopath/src/github.com/miekg/dns/duplicate_generate.go:33 +0x1ab

main.main()

	/home/travis/gopath/src/github.com/miekg/dns/duplicate_generate.go:67 +0x1516

exit status 2

duplicate.go:3: running "go": exit status 1
~~~
not related to this PR...?

**Comment by chantra** [comment]
Wouldn't this only refuse 1 out of 100 packet when we are getting saturated?
Would it be better to return REFUSED until the number of goroutines get back under the threshold?

There is pros and cons of each approaches, but I am not sure how REFUSING 1 out of 100 will help.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/dns] Add LimitReader to ..." ]
>Wouldn't this only refuse 1 out of 100 packet when we are getting saturated?

uhm, yes ... changed :-)

>Would it be better to return REFUSED until the number of goroutines get back under the threshold?

/Miek

--
Miek Gieben

**Comment by miekg** [comment]
leaving this as a way to do it, not merging

**Pull request closed without merging**
