### PR TITLE
Add Dedup function - WIP do not merge

### PR DESCRIPTION
**Pull request by miekg**
Add a function to dedup an set of RRs. For this to work nicely I needed
something to format an RR with a Sprintf like function. So add that too.
For the Sprintf to work a rdataString() for each RR would be nice: add
that too. The %r modifier in Sprintf allows you to access this.

Don't really want to add RdataString() as an exported function to each
RR, as this add a whole load of extra methods. So just a Sprintf
function.

Also add Dedup function that uses all this.

### CODE REVIEW

**Comment by miekg** [comment]
@asergeyev I could use a second pair of eyes on this. I'm working on #223 and #225. I think these changes in this PR make sense *and* are usable for users of this lib, specifically Sprintf() and maybe rdataString too? Anyway I you could take a small look? That would be really cool! thanks

**Comment by asergeyev** [comment]
Why not to dedup using wire format?

Few comments would be in lined into code...

**Comment by asergeyev** [comment]
"OK with comments"...

**Comment by asergeyev** [comment]
To comment my point about dedupping wire format....

    PackStruct(rr)

gives set of bytes, where you have TTL in 4 bytes starting at len(name)+6 (where name has final dot and +7 without it)  Idea is to pack RR, then set TTL to 0,0,0,0 and then use result as key for comparisons....

**Comment by miekg** [comment]
Re: about using wiredata: that makes sense, but you cannot use a map then as keys can't be sliced types.

**Comment by asergeyev** [comment]
You can convert buffer to string and then reuse buffer to wirepack next rr.
But I'm not pushing on it, it's just another approach.

**Comment by miekg** [comment]
That's true and memory wise, it will only cost the extra allocation for the []byte. I like it.

**Comment by asergeyev** [comment]
It would be ideal at some way of evolving go-dns to have dns/wire sublib that operates on bytes only... No strings or structs yet :)) But it sounds scary and time-costly to get into such thing...

**Comment by miekg** [comment]
Yeah, but most of the time, having such things as strings and structs is just so easy :-)

**Comment by asergeyev** [comment]
I agree... for a general purpose lib anyway...

If you make some decision on how you want to do it (with pack/ or with rdatastring) and need another review just mention it please... I'll hold off from code comments until then.

I really do not have a good opinion about adding/keeping rdataString method and making it public. On one side I found those things useful in past (Net::DNS life and so on), but I also do not see it being a necessity, everything I've done with go-dns so far was easy to write without having separate Stringer for rdata... and once you make it public it's hard to pull back :)

**Comment by miekg** [comment]
Agreed :-)
I'm going with your suggestion to use the binary data, will have something ready in the next our to tmrw :)

**Pull request closed without merging**
