### PR TITLE
Provide more control over server writing and make UDP support extendable

### PR DESCRIPTION
**Pull request by tmthrgd**
This replaces the much more complicated interface proposed in #918 (see https://github.com/miekg/dns/pull/918#issuecomment-470321738) with a different approach that should allow all the same control over the server.

**Note:** This is still lacking tests and so isn't ready to merge yet.

Closes #918

/cc @jrajahalme

### CODE REVIEW

**Comment by miekg** [comment]
I don't like it, the old way looks way more saner and we're catering/changing this code for a very specific use-case.

We also have the incredible awfully named Decorators in here as well.

**Comment by miekg** [comment]
A proper(er?) way to sidestep this all is, I think, to copy the http.RoundTripper interface and add a default one in the lib

**Comment by tmthrgd** [comment]
@miekg Could you elaborate on that idea?

**Comment by miekg** [comment]
oh fuck, this is server side, I was thinking client. Maybe something like http.Transport makes sense for a server as well?

**Comment by jrajahalme** [comment]
@miekg In the meanwhile I've tried to cope with the existing level of UDP support by limiting the Cilium policy language to only allow proxying for UDP on port 53 (see https://github.com/cilium/cilium/pull/7566). This should be no big deal as everyone is using DNS on it's standard port. For this to work with TPROXY without any DNS proxy changes the DNS proxy has to bind to port 53, but this interferes with any DNS server running on the same host, so coping with this would be too much of a restriction on the Cilium deployment.

The reason why the proxy has to bind to port 53 is that the UDP response is sent using the the listener socket, so the source port on the responses is going to be the same as the bound port for receiving. While TPROXY would allow the proxy receiving packets sent on port 53 to any arbitrary port (say, 5353), the responses will have the source port of the actual socket (here 5353).

The reason we want to move to TPROXY is that it allows the Cilium datapath to be significantly simplified and that there is some inherent raciness in iptables REDIRECT method (see https://www.kernel.org/doc/Documentation/networking/tproxy.txt). For TCP TPROXY is very easy and requires no changes in the proxy. Unfortunately, due to UDP being connectionless, some new oob/control data has to be dealt with in both reception and sending.

The approach I proposed in #918 may not be perfect, but it is an straightforward extension of the structures you already have for UDP transport; the only real change is the use of Go interfaces instead of structs to allow for extension on the library user side. I've run this code in testing for more than a month now, and have been happy with the results.

Would it be too much to ask to have another look at #918, now that we know the alternatives are not particularly beautiful either? When I researched this I found other people have asked for something similar in the past, so hopefully Cilium is not the only project that would benefit from this.

In the first round of review, dealing with the buffer pooling was an eyesore, and I'd be more than happy to amend it to any direction you may wish.

**Comment by jrajahalme** [comment]
@tmthrgd @miekg FYI, I posted just posted #955, a cleaned up and rebased version of the UDP extensibiilty PR. Moving the pooling away from server.go made it quite a bit cleaner. I also renamed and restructured the interfaces/methods in udp.go according to the feedback you provided on the original PR. I hope you'll take a fresh look, and maybe start by checking out the diffs on [server.go](https://github.com/miekg/dns/pull/955/files#diff-34c6b408d72845d076d47126c29948d1), as I was quite happy how it turned out :-)

**Comment by tmthrgd** [comment]
I’m going to close this PR for now and propose changing the `Writer` interface to be this PRs `ConnWriter` whenever a plan emerges for a v2 of this library. Otherwise, I don’t see this being merged at present.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/dns] Provide more contro..." ]
>Closed #949.

So I don't think I want to see this extensible.

I addedd a thing for a company at some point in time: 'Server.Unsafe', because 
they (and only they) needed it. It stayed in the lib for 4 years, after which I 
reached out if they still needed that. 1) They didn't know it was there 2) they 
hadn't used it for years - if ever. No one else needed or wanted this.

I'm not going to repeat that mistake. This falls squarly in the same boat. This 
PR is small enough to be applied in your private fork for the time being.

This is a generic DNS library. Iff someone else has the same problem in the next 
few years we can discuss this again, for now I don't see what we need add code 
to make this possible.

/Miek

--
Miek Gieben

**Pull request closed without merging**
