### PR TITLE
Update RSA Exponent Limit

### PR DESCRIPTION
**Pull request by everclear**
publicKeyRSA() should allow an exponent of F5.

### CODE REVIEW

**Comment by miekg** [comment]
does the go crypto library support this?

**Comment by everclear** [comment]
The exponent is an `int` in the crypto library and this size exponent works just fine on a 64bit OS.
I've altered the check to also ensure that expo fits within the max capacity of the int type on a 32bit OS.

**Comment by miekg** [comment]
Has this issue been fixed: https://github.com/golang/go/issues/3161

**Comment by miekg** [comment]
Stale PR and not responding to questions.

**Pull request closed without merging**
