### PR TITLE
Fix https://github.com/miekg/dns/issues/1131 - invalid LOC parsing

### PR DESCRIPTION
**Pull request by Fluepke**
Also implemented a test to point out, that this really fixes https://github.com/miekg/dns/issues/1131

### CODE REVIEW

**Comment by andrewtj** [comment]
I can't seem to find anything that suggests implementations should round values like `16m` to `10m` in the spec. Is that a BIND-ism or have I overlooked something?

**Comment by Fluepke** [comment]
The rounding is due to RFC1876 Section 2:

The diameter of a sphere enclosing the described entity, in
             centimeters, expressed as a pair of four-bit unsigned
             integers, **each ranging from zero to nine**, with the most
             significant four bits representing the base and the second
             number representing the power of ten by which to multiply
             the base.  This allows sizes from 0e0 (<1cm) to 9e9
             (90,000km) to be expressed.  This representation was chosen
             such that the hexadecimal representation can be read by
             eye; 0x15 = 1e5.  Four-bit values greater than 9 are
             undefined, as are values with a base of zero and a non-zero
             exponent.

Some implementations handle this differently and allow for example a mantissa of 0xB to express values like 11 meters.

IMHO we should stick to the RFC.

**Comment by andrewtj** [comment]
I wasn’t suggesting that the 0 to 9 clamp should be ignored. By my read there’s nothing in the RFC to suggest rounding rather than returning an error. Is there anything in the RFC that suggests that behaviour or is it done because that’s what BIND does?

**Comment by Fluepke** [comment]
Umm, I should be only reporting an “error” (i.e. ok==false) when the exponent is larger than 9, thus a value like 16m would be reported as okay and it would be rounded to 10m. This is also the bind behavior.

We can however also round 16m to 20m. Shall I adapt the PR accordingly?

**Comment by Fluepke** [comment]
Dear @tmthrgd, I have provided an example in this [zone file](https://gitlab.com/fluepke/nixos-config/-/blob/master/dns/fluep.ke.zone#L6) which is hosted at `ns1.fluep.ke` and `ns2.fluep.ke` using `BIND 9.14.12 (Stable Release)`

The record is
```zone
example		IN	LOC	15 5 54.000 N 108 32 46.000 W 408000.00m 16m 11m 10000m
```

You can retrieve the zone (this is allowed on purpose) or just the record using
```bash
dig axfr fluep.ke @ns1.fluepke
dig LOC example.fluep.ke
```

which results in the value being rounded as in my implementation
```zone
example.fluep.ke.	3600	IN	LOC	15 5 54.000 N 108 32 46.000 W 408000.00m 10m 10m 10000m
```

**Comment by andrewtj** [comment]
> On 5 Jul 2020, at 11:08 pm, Fabian Lüpke <notifications@github.com> wrote:
> 
> 
> Umm, I should be only reporting an “error” (i.e. ok==false) when the exponent is larger than 9, thus a value like 16m would be reported as okay and it would be rounded to 10m. This is also the bind behavior.

Let met put it another way: invalid (cannot be round tripped) values are being coerced into ones that can, not because the RFC says to (it's undefined at best), but because that's what BIND does. That's fine, I just wanted to be clear on where the behaviour is coming from.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/dns] Fix https://github...." ]
>
>
>> On 5 Jul 2020, at 11:08 pm, Fabian Lüpke <notifications@github.com> wrote:
>>
>>
>> Umm, I should be only reporting an “error” (i.e. ok==false) when the exponent
>is larger than 9, thus a value like 16m would be reported as okay and it would
>be rounded to 10m. This is also the bind behavior.
>
>Let met put it another way: invalid (cannot be round tripped) values are being
>coerced into ones that can, not because the RFC says to (it's undefined at
>best), but because that's what BIND does. That's fine, I just wanted to be
>clear on where the behaviour is coming from.

please add this paragraph as a comment on a sane spot in this PR, so we don't loose this
context that it's not really defined in the spec, but BIND does it

**Comment by miekg** [comment]
ping?

**Comment by Fluepke** [comment]
I have added the comment.

**Comment by Fluepke** [comment]
Okay, this was apparently fixed by https://github.com/miekg/dns/commit/da812eed45cba1ce4c978e746039483064b8f92d

**Pull request closed without merging**
