### PR TITLE
Spelling

### PR DESCRIPTION
**Pull request by jsoref**
This PR corrects misspellings identified by the [check-spelling action](https://github.com/marketplace/actions/check-spelling).

The misspellings have been reported at https://github.com/jsoref/miekg-dns/commit/3b877f1b61f8504feb6fe4a6411680b71cafb7ce#commitcomment-47099553

The action reports that the changes in this PR would make it happy: https://github.com/miekg/dns/commit/3ae7b3761de13bae866cb5e9b325ee0c2b5b5d3a

Note: this PR does not include the action. If you're interested in running a spell check on every PR and push, that can be offered separately.

### CODE REVIEW

**Comment by miekg** [comment]
some are indeed valid, but for some reason this also touches variable names, so nack

**Comment by jsoref** [comment]
Quite willing to drop things.

It's considerably cheaper for me to spell check everything than it is to only spell check some things.

`prever` is changed because it isn't a word and what it meant wasn't obvious. Its companions were changed for consistency. (`nexts` also isn't a word. The plural of `next` is `next` – same for `previous`. They are both [uncountable](https://www.dictionary.com/browse/uncountable) nouns)

Each word is changed in a commit, let me know which words/commits you dislike, and I'll drop them.

**Comment by jsoref** [comment]
I've split the bits which I suspect you dislike to https://github.com/jsoref/miekg-dns/commits/spelling-full

Note that:
996380a9 (3151ed3)
is probably related to https://tools.ietf.org/html/rfc3123
and you generally write it like this: https://github.com/miekg/dns/search?q=afdlen

**Review by miekg — APPROVED** [review]

**Comment by jsoref** [comment]
Would you like the action to help you prevent merging future errors?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/dns] Spelling (#1222)..." ]
>Would you like the action to help you prevent merging future errors?

on the fence... A spelling error should not be grave enough that the checks on the PR
fail, so I'm going with 'no' atm

**Comment by jsoref** [comment]
You can choose which checks are required for merging (by default newly added checks are _not_ considered for merging), and you could also set it so that they don't actually "fail" if you're afraid that the ❌ would scare people.

**Pull request merged**
