### PR TITLE
Make Server.Shutdown not wait for graceful shutdown

### PR DESCRIPTION
**Pull request by tmthrgd**
In b0dc93d276 the behaviour of `Shutdown` was changed to wait indefinitely for graceful shutdown. This reverts it to it's previous behaviour of terminating immediately.

`ShutdownContext` is now the only wait to perform a graceful shutdown.

This doesn't technically solve the problem as to why connections were getting stuck in `net.(*UDPConn).ReadMsgUDP`, but it makes `Shutdown` safe to use again.

Updates #756

### CODE REVIEW

**Comment by miekg** [comment]
I would rather find the root cause here; considering the amount work that went into this. I need to get some coredns work out of the way, but I'll try to take a look.

**Comment by tmthrgd** [comment]
Graceful shutdown will still work using the `ShutdownContext` call in this case. I’ll keep looking into why the read isn’t being interrupted.

**Comment by tmthrgd** [comment]
@miekg Another option similar to this, is to make `Shutdown` have a timeout by default (perhaps say one minute) so it can't block forever (which is the problem at the moment). If someone wants to wait forever, they can still use `ShutdownContext` with `context.Background()`.

**Comment by miekg** [comment]
(should look at the code)

But how can we have that problem? Why is it blocked when we initiated a
shutdown, at some point the queue should be empty and we can stop?

**Comment by tmthrgd** [comment]
@miekg For the shutdown to be graceful, we have to wait until all the inflight requests are finished before closing the UDP connection. `SetReadDeadline` is used to unblock reads (exactly as is done in the standard library), but for some reason it doesn't always unblock and the read never finishes causing the whole thing to block and timeout.

**Comment by tmthrgd** [comment]
@miekg Ohhhhhh I think I've figured it out. Let's see if I can fix it properly.

**Pull request closed without merging**
