### PR TITLE
Implement attempts in DNS Client

### PR DESCRIPTION
**Pull request by jvgutierrez**
This PR implements attempts in DNS client resolution.

If Client.attempts is not set defaults to 1, mimicking the behaviour the library had before adding the attempts implementation

### CODE REVIEW

**Comment by miekg** [comment]
I rather leave this out of the library and let user implement their own re-try logic. 
Should retry only be done for UDP? Does it makes sense for TCP? Retry on time out as well? etc. etc.

**Comment by jvgutierrez** [comment]
@miekg IMHO this should be the way to support attempts setting from resolv.conf

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/dns] Implement attempts ..." ]
>@miekg IMHO this should be the way to support attempts setting from resolv.conf

hmmm, not so sure. Another question that arises; should a client try another
nameserver while this one is being re-tried? How do you convey that information?
What if you have 1000 diff queries inflight and they all retry. I mean that
retry behavior should be smarter then just an for-loop and might also contain
backoff and jitter.

I think it is best to keep this code super simple and allow (force?) user to
define their own retry stuff.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/dns] Implement attempts ..." ]
>Closed #449.

In the future is better to open a bug first to discuss various trade off, before
heading off and implementing it (granted this was a small change)

**Pull request closed without merging**
