### PR TITLE
Fix authorship of my commits

### PR DESCRIPTION
**Pull request by middelink**
Due to CLA assignment.

### CODE REVIEW

**Comment by miekg** [comment]
This PR prolly does do what want it to do? 42 commits? Might need a rebase on master?

**Comment by middelink** [comment]
Well, that was my point in the emails I sent to you directly. I had to do a rebase to fix the  authors on the first 3 patches (for the CLA) and as a result git thinks everything behind it has changed whereas in reality only some metadata changed.

**Comment by andrewtj** [comment]
Could this be a job for a mailmap?

**Comment by middelink** [comment]
I'm not sure what the relevance of mailmap here is. That looks like a way of creating git summaries, possible mapping different emails to the author. (https://www.kernel.org/pub/software/scm/git/docs/git-shortlog.html) None of that applies. For me to be able to sign the CLA my company REQUIRES me to use the companies email address. Therefore the 3 patches needs to contain that email. If not, no CLA. *shrugs*

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/dns] Fix authorship of m..." ]
>I'm not sure what the relevance of mailmap here is. That looks like a way of 
>creating git summaries, possible mapping different emails to the author.  
>(https://www.kernel.org/pub/software/scm/git/docs/git-shortlog.html) None of 
>that applies. For me to be able to sign the CLA my company REQUIRES me to use 
>the companies email address. Therefore the 3 patches needs to contain that 
>email. If not, no CLA. *shrugs*

Can you just edit (and amend) those commits to contain a new email address?
(which is probably what you tried here).

I haven't gone over the numerous replies (and bounces) that I received on my
CLA email.

**Comment by middelink** [comment]
@miekg This is indeed what I did, rebase and amend the email addresses of the 3 patches. As I wrote in the direct email, it might be better you do that yourself (with direct write access on the master repo), as it looks like the github pull request gets confused by the rebase and makes it one big commit. (it would also give you confidence no code was changed, as I'm sure you are not going line by line over all the commits :P)

**Comment by miekg** [comment]
Ack.

Just to be lazy here, what are the commit hashes for these?

@miekg <https://github.com/miekg> This is indeed what I did, rebase and
amend the email addresses of the 3 patches. As I wrote in the direct email,
it might be better you do that yourself (with direct write access on the
master repo), as it looks like the github pull request gets confused by the
rebase and makes it one big commit. (it would also give you confidence no
code was changed, as I'm sure you are not going line by line over all the
commits :P)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/miekg/dns/pull/383#issuecomment-230716415>, or mute the
thread
<https://github.com/notifications/unsubscribe/AAVkW9lV5ThrG_S5cpr3vk2G_V6zkhBCks5qS24FgaJpZM4JFNor>
.

**Comment by middelink** [comment]
$ git log | grep -B1 middelink@poly
commit 5fc21d26a1a457c9fbb59ca2687ad7ac7cf259e9
Author: Pauline Middelink <middelink@polyware.nl>
--
commit 13a6137d7997c461e4199c38c47e8f53950b1f16
Author: Pauline Middelink <middelink@polyware.nl>
--
commit 77b60828edaf81e7c5f784328119c1e7bce60d01
Author: Pauline Middelink <middelink@polyware.nl>

**Comment by miekg** [comment]
I'm rethinking this whole CLA business (and what (if any) benefits it would give to this project)

**Pull request closed without merging**
