### PR TITLE
Add support for HmacSHA512 algorithm in TSIG

### PR DESCRIPTION
**Pull request by flebarbe**
The server I need to sync with requires the use of HMAC-SHA512. Implement that.

### CODE REVIEW

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[dns] Add support for HmacSHA512 al..." ]
>The server I need to sync with requires the use of HMAC-SHA512. Implement that.
>You can view, comment on, or merge this pull request online at:
>
>  https://github.com/miekg/dns/pull/175
>
>-- Commit Summary --
>
>  * Add support for HmacSHA512 algorithm in TSIG

bonus points if you add HmacSHA384 as well.

/Miek

--
Miek Gieben

**Comment by flebarbe** [comment]
I understand that it would be interesting to have it for completeness. I hesitated when I added 512. However, I would have no way to test it, that's why I didn't do it.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [dns] Add support for HmacSHA51..." ]
>I understand that it would be interesting to have it for completeness. I hesitated when I added 512. However, I would have no way to test it, that's why I didn't do it.

Yes, testing this is tricky, esp. when you want to test it against something
like BIND of NSD.

I'll try to trick travis into installing and upping a nameserver for testing.

/Miek

--
Miek Gieben

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [dns] Add support for HmacSHA51..." ]
>I understand that it would be interesting to have it for completeness. I hesitated when I added 512. However, I would have no way to test it, that's why I didn't do it.

https://github.com/miekg/dns/issues/176

/Miek

--
Miek Gieben

**Pull request merged**
