### PR TITLE
Expose RR and RR Header Len

### PR DESCRIPTION
**Pull request by matje**
Related to issue #316

### CODE REVIEW

**Comment by miekg** [comment]
I think it makes most sense to do this in the same way as we did `Copy`, https://github.com/miekg/dns/blob/85b661b2a6fc95a5a83e66d7730c4bc0b6e9c99e/msg.go#L1893

This would be a minimal I think Len() would then automatically work for `RR_Header` as that is an RR as well.

Also: currently the tests don't compile

**Comment by andrewtj** [comment]
Although not relevant to implementing this as `func Len(RR) int`, for future reference `types_generate.go` builds `ztypes.go` via `go generate`.

**Comment by matje** [comment]
@miekg It's still on my todo list

**Comment by matje** [comment]
Easier to close this PR and create a new one with the easier fix, see #333

**Pull request closed without merging**
