### PR TITLE
update golang.org/x/crypto version

### PR DESCRIPTION
**Pull request by MrIroe**

### CODE REVIEW

**Comment by miekg** [comment]
confused by travis returning an error on build

**Comment by miekg** [comment]
oh you might want to run 'go generate' as well

**Comment by MrIroe** [comment]
alright will do, and update pr

**Comment by semihalev** [comment]
There is a test error on dev version of Golang. Looks like int to string yields doesn't acceptable anymore. Like this: `string(63)` in [msg_test.go#L136](https://github.com/miekg/dns/blob/master/msg_test.go#L136)

**Comment by tmthrgd** [comment]
@semihalev That's golang/go#3939 and golang/go#32479. Those conversions need to be replaced.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/dns] update golang.org/x..." ]
>@semihalev That's golang/go#3939 and golang/go#32479. Those conversions need to
>be replaced (edit: in a separate PR).

see https://github.com/miekg/dns/pull/1117

**Pull request closed without merging**
