### PR TITLE
Add AXFR tests run against SIDN's DNS Workbench

### PR DESCRIPTION
**Pull request by andrewtj**
This adds test transfers from SIDN's DNS Workbench (mentioned in #174). The tests are behind a build tag to avoid unintentionally hitting their servers.

All the tests fail for one reason or other. I haven't been able to perform a transfer using `dig` from their Knot, YADIFA or PowerDNS installs however their NSD3, NSD4 and BIND9 installs do seem to work. I haven't dug into why `go dns` fails where `dig` succeeds. Might be that I'm doing something silly ;)

### CODE REVIEW

**Comment by miekg** [comment]
Thanks for this. I think it make sense to move the other test over as well. @tjeb this workbench will stay up for the foreseeable future?  And do you guys mind the "extra" load?

**Comment by tjeb** [comment]
Miek Gieben schreef op 7-8-2015 om 08:27:
> Thanks for this. I think it make sense to move the other test over as
> well. @tjeb <https://github.com/tjeb> this workbench will stay up for
> the foreseeable future? And do you guys mind the "extra" load?
>

It will, and we don't, as long as you keep in mind that we also don't 
provide uptime guarantee (best effort and all that) :)

Jelte

**Comment by miekg** [comment]
Cool :-)

**Comment by miekg** [comment]
Ok, If I kill the NSAP record a lot more starts working:
```
% go test -tags SIDN -run "AXFR.*_NONE"
--- FAIL: TestAXFR_POWERDNS_NONE (0.06s)
	sidnxfr_test.go:75: EOF
--- FAIL: TestAXFR_YADIFA_NONE (0.05s)
	sidnxfr_test.go:75: dns: no SOA
FAIL
exit status 1
FAIL	github.com/miekg/dns	0.351s
```

**Comment by miekg** [comment]
powerdns is fooked:
```
% dig @powerdns.sidnlabs.nl axfr types.wb.sidnlabs.nl 

; <<>> DiG 9.9.5-3ubuntu0.4-Ubuntu <<>> @powerdns.sidnlabs.nl axfr types.wb.sidnlabs.nl
; (2 servers found)
;; global options: +cmd
types.wb.sidnlabs.nl.	86400	IN	SOA	nsd.sidnlabs.nl. hostmaster.sidnlabs.nl. 1395909394 3600 600 1814400 3600
;; communications error to 2a00:d78:0:712:94:198:159:26#53: end of file
```

**Comment by miekg** [comment]
Knot seems to do something different with tsig...

```
% go test -tags SIDN -run "AXFR"       
--- FAIL: TestAXFR_KNOT_MD5 (0.07s)
	sidnxfr_test.go:75: dns: bad authentication
--- FAIL: TestAXFR_KNOT_SHA1 (0.07s)
	sidnxfr_test.go:75: dns: bad authentication
--- FAIL: TestAXFR_KNOT_SHA256 (0.06s)
	sidnxfr_test.go:75: dns: bad authentication
--- FAIL: TestAXFR_POWERDNS_NONE (0.08s)
	sidnxfr_test.go:75: EOF
--- FAIL: TestAXFR_POWERDNS_MD5 (0.08s)
	sidnxfr_test.go:75: dns: no SOA
--- FAIL: TestAXFR_POWERDNS_SHA1 (0.06s)
	sidnxfr_test.go:75: dns: no SOA
--- FAIL: TestAXFR_POWERDNS_SHA256 (0.06s)
	sidnxfr_test.go:75: dns: no SOA
--- FAIL: TestAXFR_YADIFA_NONE (0.07s)
	sidnxfr_test.go:75: dns: no SOA
--- FAIL: TestAXFR_YADIFA_MD5 (0.05s)
	sidnxfr_test.go:75: dns: no SOA
--- FAIL: TestAXFR_YADIFA_SHA1 (0.06s)
	sidnxfr_test.go:75: dns: no SOA
--- FAIL: TestAXFR_YADIFA_SHA256 (0.06s)
	sidnxfr_test.go:75: dns: no SOA
FAIL
exit status 1
FAIL	github.com/miekg/dns	1.585s
```

**Comment by miekg** [comment]
Knot fails with dig as well
```
% dig -y wb_md5:Wu/utSasZUkoeCNku152Zw==   @knot.sidnlabs.nl axfr types.wb.sidnlabs.nl  
;; Couldn't verify signature: tsig indicates error

; <<>> DiG 9.9.5-3ubuntu0.4-Ubuntu <<>> -y wb_md5 @knot.sidnlabs.nl axfr types.wb.sidnlabs.nl
; (2 servers found)
;; global options: +cmd
wb_md5.			0	ANY	TSIG	hmac-md5.sig-alg.reg.int. 1439127569 300 0  39744 BADKEY 0 
; Transfer failed.
```

**Comment by Habbie** [comment]
@tjeb your powerdns install appears to have trouble with rkey/type57, any idea why?

**Comment by tjeb** [comment]
On 08/09/2015 03:40 PM, Miek Gieben wrote:
> |dig -y wb_md5:Wu/utSasZUkoeCNku152Zw==   @knot.sidnlabs.nl axfr types.wb.sidnlabs.nl  |

updated knot to version 2, this should work now

**Comment by miekg** [comment]
Yep, knot2 works. Thanks.

**Comment by miekg** [comment]
Btw: think all tests should be moved over. OTOH I would be nice to have the tests run against a special dns server that I host to get some stats from that.

**Comment by andrewtj** [comment]
@miekg move them all into xfr_test.go? I should be able to do that later today. What stats are you interested in?

**Comment by miekg** [comment]
Yes, moving them back in xfr_test.go. I'm also thinking about other test that I do against remote servers (my own vps atm). Ideally this should then be hidden with a -net tag.

I would be cool to have some webpage with the (test) requests that hit this server, qps, remote nets connecting, failures,  timeouts that sort of things.

**Comment by tjeb** [comment]
I have made a note of adding something like a stats page for the workbench servers, but I must warn it will be pretty low on my priority list in the foreseeable future :)

**Comment by andrewtj** [comment]
@miekg any comments on fe0937f?

**Comment by miekg** [comment]
None, actually.

**Pull request merged**
