### PR TITLE
Trying to revert the worker code

### PR DESCRIPTION
**Pull request by miekg**
this is an attempt to revert 98a1ef45. Left with a few conflicts and not
100% what to bring back because the reverted commit is a bit old.

But half way there, at least.

### CODE REVIEW

**Comment by miekg** [comment]
probably makes more sense to go forward; i.e. just delete the current code, then to actually revert this older commit. I'll try that as well.

**Comment by miekg** [comment]
also want to remove w.msg from `response`, because its not part of the response. This triggers question about disposeBuffer

**Comment by tmthrgd** [comment]
I wouldn’t try a `git revert` on this because it has changed a lot since then. If we ditch the worker code, we can go back to some of the cleaner function signatures that were there before the workers. In that case the message buffer and can be passed directly because it is needed up until `disposeBuffer`.

**Pull request closed without merging**
