### PR TITLE
Add tsig on Transfer.Out()

### PR DESCRIPTION
**Pull request by WeipengSun**
I'm doing a project of dns master, I found that the DNS library was not supported adding tsig when using Transfer.Out to reply Axfr or Ixfr request.
My idea is that put the tsig information from request.

### CODE REVIEW

**Comment by miekg** [comment]
This is done in https://github.com/miekg/dns/blob/master/xfr.go#L229
why doesn't that work for you? What does this fix and what test would fail?

**Comment by WeipengSun** [comment]
When using transfer out to send out an axfr/ixfr result, Envelope can only set Answer section, but not additional section(Tsig RR). function m.IsTsig in ReadMsg always return nil.

**Comment by miekg** [comment]
please add a test.

**Comment by WeipengSun** [comment]
--- FAIL: TestClientRemote (2.00s)
    remote_test.go:14: failed to exchange: read udp 172.17.0.25:58446->176.58.119.54:53: i/o timeout

I doesn't know how to recheck of travis-ci

**Pull request closed without merging**
