### PR TITLE
Use and vendor golang.org/x/net/ipv4 and golang.org/x/net/ipv6

### PR DESCRIPTION
**Pull request by fastest963**
Removed the `internal/socket` and used `golang.org/x/net/ipv4` and `golang.org/x/net/ipv6` adding them with dep to the vendor folder.

Additionally, I removed the `udp_linux.go` in favor of using ipv4/ipv6 for cross-platform support. We don't quite have Windows support since that will be coming with go 1.10 (and then we can use build flags to exclude `udp_windows.go` on < 1.10) and is tracked in #571.

I tried to add tests to test as much of the OOB functionality as possible. I will be testing in production with a newer build of CoreDNS to verify everything on Linux.

### CODE REVIEW

**Comment by fastest963** [comment]
Apparently travis-ci doesn't have any IPv6 support so the test for `[::1]:0` will log and not be run. Running that locally for me works but I'm not sure how to get that tested via travis-ci.

**Comment by fastest963** [comment]
We don't have a way to test for IPv6 or IPv4 in `parseDstFromOOB` so I left it defaulting to IPv6 and then falling back to IPv4. If you have an IPv6 kernel and don't specifically listen on IPv4, then the out-of-band data will be in IPv6 format (with :ffff: in front of IPv4) no matter if the packet was actually from IPv4 or IPv6 so I assume that's probably the more common case. We could look at the first few bytes of the data and see if there's a level of `0` or `41` to determine the format but that wouldn't be cross platform. I don't think the overhead of doing both is worth the optimization to only 1 or the other at this point.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [miekg/dns] Use and vendor gola..." ]
>Apparently travis-ci doesn't have any IPv6 support so the test for `[::1]:0` will log and not be run. Running that locally for me works but I'm not sure how to get that tested via travis-ci.

No, you can't with travis :-(

**Comment by miekg** [comment]
Is everything looking Ok from your side? If so; I will merge this.

**Comment by miekg** [comment]
I'm going ahead with this. CoreDNS 1.0.0 will be announced today and 1.0.1 dev has started, meaning plenty of time for me to see if this works or not.

**Comment by fastest963** [comment]
@miekg yes we've been running this in production with CoreDNS since the 30th and it seems to be working fine. Sorry, somehow I missed your comment.

**Comment by johnbelamaric** [comment]
@fastest963 if you are running CoreDNS in production would you mind adding yourself to https://github.com/coredns/coredns/blob/master/ADOPTERS.md ? It will help as we move toward incubation status in the CNCF.

**Pull request merged**
